talloc: remove default packages from the packages list since empty
populate_sdk fails with following message:
error: talloc-dev-2.1.1-r0 requires talloc = 2.1.1-r0

these packages are empty,remove them from the package list